from pathlib import Path
from html import escape
from urllib.parse import quote
import re

root = Path(__file__).resolve().parents[1] / 'dist'
home = (root / 'index.html').read_text(encoding='utf-8')
if 'expansion.css' not in home:
    home = home.replace('</head>', '<link rel="stylesheet" href="expansion.css"></head>')
services = [
 dict(slug='electricidad',name='Servicios eléctricos',category='electricidad',title='ENERGÍA QUE<br>FUNCIONA CONTIGO.',intro='Desde una nueva instalación hasta una falla que necesita atención. Revisamos las necesidades eléctricas de tu hogar, comercio o negocio para definir una solución adecuada.',items=[('Instalaciones eléctricas','Instalación y adecuación de circuitos, tomacorrientes y puntos eléctricos según las necesidades del espacio.'),('Diagnóstico de fallas','Revisión de interrupciones, conexiones y componentes para identificar el origen de una falla y definir su reparación.'),('Tableros de distribución','Evaluación e instalación de tableros y sus componentes, considerando las cargas y la distribución de los circuitos.'),('Iluminación','Instalación y renovación de puntos de luz para interiores y exteriores según el uso de cada área.'),('Protección de voltaje','Evaluación de soluciones de protección compatibles con los equipos y las condiciones de la instalación.')],when='Si estás remodelando, ampliando tu negocio o necesitas revisar una falla, podemos evaluar tu instalación y conversar sobre el trabajo necesario.',prepare='Indícanos el tipo de espacio, qué necesitas instalar o qué falla presenta. Las fotos del área o del equipo pueden ayudarnos a entender la consulta, sin manipular la instalación.',faqs=[('¿Pueden revisar una falla antes de cotizar la reparación?','Sí. El diagnóstico permite definir el alcance del trabajo. Escríbenos para coordinar la evaluación y consultar sus condiciones.'),('¿Los materiales están incluidos?','Los materiales y la mano de obra se definen en cada cotización. Confirmaremos contigo los componentes necesarios antes de coordinar el trabajo.'),('¿Trabajan en hogares y negocios?','Atendemos consultas para hogares, comercios y negocios. Comparte la ubicación y los detalles para confirmar la atención de tu proyecto.')]),
 dict(slug='climatizacion',name='Climatización',category='climatizacion',title='TU ESPACIO.<br>EL CLIMA IDEAL.',intro='Instalación, mantenimiento y reparación de sistemas de aire acondicionado para que tu espacio mantenga el confort que necesitas.',items=[('Instalación de equipos','Revisión de las condiciones del espacio y coordinación de la instalación del aire acondicionado y sus conexiones.'),('Mantenimiento preventivo','Revisión del sistema y labores de mantenimiento según el estado del equipo, su uso y las recomendaciones del fabricante.'),('Diagnóstico y reparación','Evaluación de problemas de enfriamiento, funcionamiento, ruidos o drenaje para determinar la intervención necesaria.'),('Revisión de la instalación','Evaluación de las conexiones, el drenaje y la ubicación del equipo como parte del alcance acordado.')],when='Para instalar un equipo, programar su mantenimiento o revisar cambios en su funcionamiento, empezamos por conocer tu espacio y el sistema que utilizas.',prepare='Envíanos la marca y el modelo si los conoces, fotos del equipo, el tamaño aproximado del espacio y una descripción de lo que necesitas.',faqs=[('¿Cada cuánto se necesita mantenimiento?','La frecuencia depende del uso, el ambiente y las recomendaciones del fabricante. Podemos revisar esas condiciones contigo para proponer una periodicidad.'),('¿Puedo consultar por un equipo que ya tengo?','Sí. Indícanos la marca, el modelo y si necesitas instalación, mantenimiento o diagnóstico.'),('¿Puedo solicitar equipo e instalación?','Puedes consultar ambos. La disponibilidad del equipo y el alcance de la instalación se confirman por separado en la cotización.')]),
 dict(slug='ventanas-y-puertas',name='Ventanas y puertas',category='ventanas',title='ABRE PASO<br>A TU PROYECTO.',intro='Fabricación e instalación de ventanas y puertas que responden a las medidas, el uso y los acabados que necesitas para tu espacio.',items=[('Fabricación para tu espacio','Definición de medidas, apertura, materiales y acabados de acuerdo con los requerimientos del proyecto.'),('Instalación de ventanas','Preparación y colocación según las condiciones del área y las especificaciones acordadas.'),('Instalación de puertas','Coordinación de medidas, sistema de apertura y componentes para una instalación funcional.'),('Acabados y herrajes','Selección de detalles de terminación y componentes compatibles con el diseño y el uso previsto.')],when='Para completar una obra, renovar un espacio o reemplazar una puerta o ventana, revisamos las medidas y las condiciones de instalación antes de definir la solución.',prepare='Comparte fotos, medidas aproximadas, cantidad de piezas y el tipo de apertura o acabado que tienes en mente. Las medidas finales se confirman antes de fabricar.',faqs=[('¿Trabajan con medidas personalizadas?','La fabricación se define según cada proyecto. Las medidas y especificaciones finales deben confirmarse antes de iniciar el trabajo.'),('¿Puedo elegir los acabados?','Cuéntanos qué acabado buscas. Revisaremos las opciones y su disponibilidad al preparar la cotización.'),('¿Cuánto tarda la fabricación?','El plazo depende de las medidas, los materiales, la cantidad de piezas y el alcance. Se confirma al evaluar el proyecto.')]),
 dict(slug='mantenimiento-electromecanico',name='Mantenimiento electromecánico',category='mantenimiento',title='TU OPERACIÓN.<br>EN MOVIMIENTO.',intro='Diagnóstico y reparación de equipos industriales y comerciales, con una evaluación que permite definir la intervención y los componentes necesarios.',items=[('Diagnóstico de equipos','Revisión del funcionamiento y de los síntomas reportados para identificar las necesidades de intervención.'),('Reparación electromecánica','Trabajo sobre los componentes eléctricos y mecánicos que formen parte del alcance acordado.'),('Revisión de componentes','Evaluación de conexiones y componentes asociados al funcionamiento del equipo.'),('Mantenimiento según el uso','Definición de necesidades de mantenimiento considerando el estado del equipo y las condiciones de operación.')],when='Cuando un equipo presenta fallas, cambios en su funcionamiento o requiere mantenimiento, una evaluación ayuda a definir los próximos pasos.',prepare='Indícanos el tipo de equipo, su uso, la marca y el modelo, los síntomas y las intervenciones previas que conozcas. Una foto de la placa de datos puede ayudar.',faqs=[('¿Qué equipos pueden evaluar?','Atendemos consultas sobre equipos industriales y comerciales. Comparte los datos del equipo para confirmar si podemos atenderlo.'),('¿Pueden cotizar sin revisar el equipo?','Podemos orientar la consulta con los datos que envíes. La reparación y sus costos dependen del diagnóstico y de los componentes necesarios.'),('¿Cómo se consiguen los repuestos?','Primero se identifica la referencia compatible. La disponibilidad, el costo y el plazo se confirman antes de acordar su uso.')])
]

header = '''<header><a class="brand" href="index.html" aria-label="E y V, inicio"><img src="assets/ev-symbol-v2.png" alt="" width="66" height="66"><span class="brand-wordmark">E & V<small>SOLUCIONES INTEGRALES</small></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menú</button><nav id="main-nav" aria-label="Navegación principal"><a href="index.html#servicios">Servicios</a><a href="tienda.html">Tienda</a><a href="index.html#nosotros">Nosotros</a><a href="index.html#proceso">Cómo trabajamos</a></nav><a class="button small header-quote" href="index.html#contacto">Cotiza tu proyecto</a></header>'''
home = re.sub(r'<header>.*?</header>', header, home, count=1, flags=re.S)
for service in services:
    pattern = r'<a href="#contacto" data-service="' + re.escape(service['name']) + r'">.*?</a>'
    home = re.sub(pattern, f'<a href="{service["slug"]}.html">Ver detalle del servicio</a>', home)
teaser = '''<section class="shop-teaser frame"><div><span class="label">PRODUCTOS + SERVICIOS</span><h2>LO QUE NECESITAS.<br>EN UN MISMO LUGAR.</h2></div><div><p>Explora nuestra tienda por categoría y consulta el producto que buscas. También puedes pedir orientación para su instalación.</p><a class="button" href="tienda.html">Explorar la tienda</a></div></section>'''
if 'shop-teaser' not in home: home = home.replace('<section id="nosotros"', teaser + '\n<section id="nosotros"', 1)
(root / 'index.html').write_text(home, encoding='utf-8')
head = home.split('<body>')[0]
footer = '<footer>' + home.split('<footer>',1)[1]

def page(title,description,content):
    page_head = re.sub(r'<title>.*?</title>', '<title>'+escape(title)+' · E & V</title>', head)
    page_head = re.sub(r'<meta name="description" content="[^"]*">', '<meta name="description" content="'+escape(description,quote=True)+'">',page_head)
    return page_head+'<body>'+header+content+footer

for number,s in enumerate(services,1):
    cards = ''.join(f'<article><span class="label">{i:02d}</span><h3>{escape(title)}</h3><p>{escape(copy)}</p></article>' for i,(title,copy) in enumerate(s['items'],1))
    faqs = ''.join(f'<details><summary>{escape(q)}</summary><p>{escape(a)}</p></details>' for q,a in s['faqs'])
    whatsapp = 'https://wa.me/18299704893?text='+quote(f'Hola, E & V. Quiero consultar sobre {s["name"].lower()}.')
    content = f'''<main id="inicio"><section class="detail-hero frame"><div class="breadcrumbs"><a href="index.html">Inicio</a><span>/</span><a href="index.html#servicios">Servicios</a><span>/</span><span>{s['name']}</span></div><span class="label">SERVICIO {number:02d} / E & V</span><h1>{s['title']}</h1><div class="detail-intro"><p>{s['intro']}</p><a class="button" href="{whatsapp}" target="_blank" rel="noopener">Consultar este servicio</a></div></section><section class="detail-scope frame"><div class="section-heading"><span class="label">EL ALCANCE</span><h2>¿EN QUÉ TE AYUDAMOS?</h2></div><div class="scope-grid">{cards}</div></section><section class="detail-context frame"><div><span class="label">PARA TU PROYECTO</span><h2>UNA SOLUCIÓN<br>PARA TU ESPACIO.</h2><p>{s['when']}</p></div><aside><span class="label">ANTES DE COTIZAR</span><h3>Cuéntanos los detalles.</h3><p>{s['prepare']}</p><p class="scope-note">El alcance, los materiales, el costo y los plazos se acuerdan en la cotización.</p><a class="text-link" href="{whatsapp}" target="_blank" rel="noopener">Hablar con E & V</a></aside></section><section class="faqs frame"><div><span class="label">RESOLVEMOS TUS DUDAS</span><h2>ANTES DE<br>EMPEZAR.</h2></div><div>{faqs}</div></section><section class="related-shop frame"><div><span class="label">SERVICIOS + PRODUCTOS</span><h2>COMPLETA TU PROYECTO.</h2><p>Consulta los productos relacionados y la posibilidad de incluir su instalación.</p></div><a class="button" href="tienda.html?categoria={s['category']}">Ver productos relacionados</a></section></main>'''
    (root / (s['slug']+'.html')).write_text(page(s['name'],s['intro'],content),encoding='utf-8')

# Product families are inquiry categories, not claims of stock or specific models.
products = [
 ('electricidad','Iluminación LED','Lámparas y luminarias','Cuéntanos el tipo de espacio, la cantidad y el tipo de iluminación que buscas.'),
 ('electricidad','Protección eléctrica','Protectores de voltaje y componentes','Indica el equipo que quieres proteger y sus datos eléctricos para consultar compatibilidad.'),
 ('climatizacion','Aires acondicionados','Equipos para tu espacio','Consulta por un equipo según las características de tu espacio y si necesitas instalación.'),
 ('climatizacion','Accesorios de climatización','Materiales para instalación','Comparte el modelo del equipo y el accesorio o material que necesitas.'),
 ('ventanas','Puertas y ventanas','Soluciones según tu proyecto','Indica medidas aproximadas, cantidad de piezas y el acabado que buscas.'),
 ('ventanas','Cerraduras y herrajes','Componentes para puertas y ventanas','Consulta por una pieza indicando el tipo de puerta o ventana y, si es posible, su referencia.'),
 ('mantenimiento','Repuestos electromecánicos','Piezas para tus equipos','Comparte la marca, el modelo y la referencia de la pieza para consultar opciones.'),
 ('mantenimiento','Componentes de control','Elementos eléctricos para equipos','Cuéntanos qué componente necesitas y sus especificaciones para revisar compatibilidad.')
]
category_names = dict(electricidad='Electricidad',climatizacion='Climatización',ventanas='Ventanas y puertas',mantenimiento='Electromecánica')
product_html=''
for i,(category,name,subtitle,description) in enumerate(products,1):
    product_html += f'''<article class="product-card" data-category="{category}" data-name="{escape(name)}"><div class="product-family"><span class="label">{category_names[category]}</span><span class="product-index">{i:02d}</span><h2>{name}</h2></div><div class="product-body"><h3>{subtitle}</h3><p>{description}</p><span class="availability">Precio y disponibilidad por consultar</span><button class="button product-add" type="button" data-product="{escape(name)}">Añadir a mi consulta</button></div></article>'''
shop = f'''<main id="inicio"><section class="shop-hero frame"><div class="breadcrumbs"><a href="index.html">Inicio</a><span>/</span><span>Tienda</span></div><span class="label">E & V / TIENDA</span><h1>PRODUCTOS PARA<br><span>TU PROYECTO.</span></h1><div class="shop-intro"><p>Explora por categoría y cuéntanos qué necesitas. Confirmamos referencias, precios y disponibilidad contigo por WhatsApp.</p><a class="text-link" href="#mi-consulta">Mi consulta (<span data-cart-count>0</span>)</a></div></section><section class="shop-catalog frame" aria-label="Catálogo de productos"><div class="shop-toolbar"><div class="category-filters" role="group" aria-label="Filtrar por categoría"><button type="button" data-filter="todos" aria-pressed="true">Todos</button>{''.join(f'<button type="button" data-filter="{key}" aria-pressed="false">{label}</button>' for key,label in category_names.items())}</div><p id="product-count" role="status">8 categorías de productos</p></div><div class="product-grid">{product_html}</div></section><section class="inquiry frame" id="mi-consulta"><div><span class="label">TU SELECCIÓN</span><h2>PREPAREMOS<br>TU CONSULTA.</h2><p>Añade los productos que te interesan y la cantidad aproximada. Revisaremos contigo las opciones y los detalles antes de acordar la compra.</p><div class="inquiry-help"><h3>¿También necesitas instalación?</h3><p>Inclúyela en tu consulta para revisar el producto y el servicio en conjunto.</p></div></div><form id="shop-inquiry"><div id="cart-items"><p class="cart-empty">Tu consulta está vacía. Añade una categoría de producto para comenzar.</p></div><div id="cart-fields" hidden><label for="shop-notes">Especificaciones o detalles del proyecto</label><textarea id="shop-notes" rows="3" maxlength="1200" placeholder="Modelo, medidas, potencia o la referencia que buscas…"></textarea><label class="check-label"><input type="checkbox" id="include-installation"> También quiero consultar la instalación</label><button class="button" type="submit">Consultar selección por WhatsApp</button><p class="form-note">Se abrirá WhatsApp para revisar y enviar tu mensaje. Esta consulta no reserva productos ni confirma un pedido.</p></div></form></section><p class="shop-feedback" role="status" aria-live="polite" id="shop-feedback"></p></main>'''
(root / 'tienda.html').write_text(page('Tienda','Consulta productos de electricidad, climatización, ventanas, puertas y mantenimiento electromecánico en E & V.',shop),encoding='utf-8')
